101 NumPy Exercises for Data Analysis (Python)

### 1. Import numpy as np and see the version
- Q. Import numpy as np and print the version number.

In [1]:
import numpy as np
print(np.__version__)

1.19.2


### 2. How to create a 1D array?
- Q. Create a 1D array of numbers from 0 to 9

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?
- Q. Create a 3×3 numpy array of all True’s

In [3]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?
- Q. Extract all odd numbers from arr

In [ ]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Solutiion
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?
- Q. Replace all odd numbers in arr with -1

In [ ]:
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Solution
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])