### 11. How to get the common items between two python numpy arrays?
- Q. Get the common items between a and b

In [10]:
# Input
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
# Solution
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?
- Q. From array a remove all items present in array b

In [12]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [13]:
# Solution
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?
- Q. Get the positions where elements of a and b match

In [14]:
# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [15]:
# Solution
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?
- Q. Get all items between 5 and 10 from a.

In [16]:
# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [17]:
# Solution

a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Method 3
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?
- Q. Convert the function maxx that works on two scalars, to work on two arrays.

#### Numpy 함수를 Array 적용하기
- 파이썬에서는 기본적으로 map 이라든지 list comprehension의 방법으로 함수를 list나 dictionary에 적용이 가능하다.
- 기존의 map함수를 이용해서도 모든 array에 적용이 가능하지만, 반환되는 형태가 array가 아니라 python list형태로 반환이 되므로 다시 array형   태로 변경이 필요하게 된다.
- 그래서 , numpy에서는 array가 기본데이터 형태이므로 바로 array에 적용하는 방법이 필요하게 된다. 그 역할을 하는 함수가 vectorize이다.

In [18]:
# Solution

def maxx(x, y):
    if x > y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
    
    

array([6., 7., 9., 8., 9., 7., 5.])