### 16. How to swap two columns in a 2d numpy array?
- Q. Swap columns 1 and 2 in the array arr.

In [2]:
# Input
import numpy as np

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# Solution
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?
- 17. How to swap two rows in a 2d numpy array?

In [4]:
# Input
arr = np.arange(9).reshape(3,3)

In [5]:
#Solution
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?
- Q. Reverse the rows of a 2D array arr.

In [6]:
# Input
arr = np.arange(9).reshape(3,3)

In [7]:
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to reverse the columns of a 2D array?
- Q. Reverse the columns of a 2D array arr.

In [8]:
# Input
arr = np.arange(9).reshape(3,3)

In [9]:
#Solution
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?
- Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [10]:
# Method 1

rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

# Method 2
rand_arr = np.random.uniform(5,10,size=(5,3))
print(rand_arr)

[[7.90029911 5.59843475 6.33602132]
 [8.58158001 6.96406533 9.61380742]
 [5.36803677 5.88019075 9.81874271]
 [8.89678047 8.9184873  5.90490856]
 [7.02508573 9.41099492 9.12838601]]
