### 21. How to print only 3 decimal places in python numpy array?
- Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [2]:
# Input
import numpy as np

rand_arr = np.random.random((5,3))

In [3]:
# Solution
np.set_printoptions(precision=3)
rand_arr

array([[0.485, 0.495, 0.564],
       [0.356, 0.039, 0.934],
       [0.332, 0.855, 0.963],
       [0.528, 0.042, 0.196],
       [0.124, 0.118, 0.615]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
- Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [4]:
# Input
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [5]:
# Solution
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

### 23. How to limit the number of items printed in output of numpy array?
- Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [6]:
# Input
a = np.arange(15)

In [8]:
# Solution
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

### 24. How to print the full numpy array without truncating
- Q. Print the full numpy array a without truncating.

In [9]:
# Input
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [11]:
# Solution
np.set_printoptions(threshold=np.inf, linewidth=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
- Q. Extract the text column species from the 1D iris imported in previous question.

In [13]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)