### 6. How to replace items that satisfy a condition without affecting the original array?
- Q. Replace all odd numbers in arr with -1 without changing arr

In [2]:
# Input
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Solution
out = np.where(arr % 2 == 1, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


### 7. How to reshape an array?
- Q. Convert a 1D array to a 2D array with 2 rows

In [5]:
# Input
arr = np.arange(10)

In [6]:
# Solution

arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?
- Q. Stack arrays a and b vertically

In [8]:
# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [10]:
# Solution

# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?
- Q. Stack the arrays a and b horizontally.

In [11]:
# Input
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [12]:
# Solution

# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?
- Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [17]:
# Input
a = np.array([1,2,3])


In [18]:
# Solution

np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])